<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\DirectoryService.Domain\DirectoryService.Domain.csproj" />
    <ProjectReference Include="..\DirectoryService.Contracts\DirectoryService.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Mazeland.Core" />
    <PackageReference Include="Mazeland.FileService.Contracts" />
    <PackageReference Include="Mazeland.FileService.Shared.Messaging" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.Seq" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <PackageReference Include="WolverineFx.Postgresql" />
    <PackageReference Include="WolverineFx.RabbitMQ" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
  </ItemGroup>

</Project>